---
title: "in_class examples"
output: html_document
date: "2023-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example: Price of houses in PA

Census data for California and Pennsylvania on housing prices,
by Census "tract"

```{r}
calif_penn = read.csv("/Users/jasperstone/Desktop/Joseph/2023 Spring/STAT404/calif_penn_2011.csv")
calif_penn
penn = calif_penn[calif_penn[,"STATEFP"]== 42,]
coefficients(lm(Median_house_value ~ Median_household_income, data=penn))

penn.coefs = coefficients(lm(Median_house_value ~ Median_household_income, data=penn))
penn.coefs
```

```{r}
allegheny.rows = 24:425
allegheny.medinc = penn[allegheny.rows,"Median_household_income"]
allegheny.values = penn[allegheny.rows,"Median_house_value"]
allegheny.fitted = penn.coefs["(Intercept)"] +
  penn.coefs["Median_household_income"]*allegheny.medinc
```

```{r}
plot(x=allegheny.fitted, y=allegheny.values,
     xlab="Model-predicted median house values",
     ylab="Actual median house values",
     xlim=c(0,5e5),ylim=c(0,5e5),
    abline(a=0,b=1,col="grey"))
```

